application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
database:
  require_ssl: false
email_client:
  smtp_host: "localhost"
  smtp_name: "Control-Parque-Vehicular localhost"
  smtp_username: "control.parque.vehicular.test@gmail.com"
  # This is not used in local
  smtp_password: "testpassword"
  smtp_port: 1025
