application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  smtp_host: "smtp.gmail.com"
  smtp_name: "Control-Parque-Vehicular"
  # Erase this username and password before commit
  smtp_username: "control.parque.vehicular.test@gmail.com"
  smtp_password: "wgumlbemejtmjajd"
  #tls= 587, ssl = 465
  smtp_port: 465
