application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  # Value return by Postmark's API documentation
  base_url: "https://api.postmarkapp.com"
  # Use the single sender email authorised on Postmark
  sender_email: "something@gmail.com"
